
package proyecto_almacen;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_personal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_personal.class.getName());
    
    conexionBD_gabriel conexionBD;
    DefaultTableModel modeloTablaPersonal = new DefaultTableModel();
    
    public frm_personal() {
        setUndecorated(true);
        initComponents();// Configuración de estado inicial para controles
        
        txt_personal.setEnabled(false);
        txt_nombre.setEditable(true);
        txt_apellidos.setEditable(true);
        txt_documento.setEditable(true);

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        this.setLocationRelativeTo(null);
        // Inicializar conexión a la BD
        conexionBD = new conexionBD_gabriel();

        if (conexionBD.getConnection() == null) {
            JOptionPane.showMessageDialog(null, "No se pudo conectar a la base de datos.",
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cargar combos auxiliares
        this.cargarCombos();

        // Configurar modelo y encabezados de la tabla
        String titulos[] = {
            "ID Personal", "ID Tipo", "Tipo Personal", 
            "ID Cargo", "Cargo", "ID Area", "Area", 
            "ID Sucursal", "Sucursal", "Nombres", "Apellidos", "Documento"
        };
        modeloTablaPersonal.setColumnIdentifiers(titulos);
        jTableman_personal.setModel(modeloTablaPersonal);

        // Ocultar IDs foráneos (columnas 1, 3, 5, 7)
        int columnasOcultas[] = {0, 1, 3, 5, 7};
        for (int col : columnasOcultas) {
            jTableman_personal.getColumnModel().getColumn(col).setMinWidth(0);
            jTableman_personal.getColumnModel().getColumn(col).setMaxWidth(0);
            jTableman_personal.getColumnModel().getColumn(col).setWidth(0);
        }

        // Asignar evento de selección a la tabla
        jTableman_personal.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableman_personalMouseClicked(evt);
            }
        });
    }

    private void cargarCombos() {
        try {
            // Tipo Personal
            jComboBox_personal.removeAllItems();
            jComboBox_personal.addItem("-- Seleccionar --");
            ResultSet rsTipo = conexionBD.cargarComboTipoPersonal();
            while (rsTipo.next()) {
                jComboBox_personal.addItem(rsTipo.getInt("id_tipo_personal") + " - " + rsTipo.getString("nombre_tipo_personal"));
            }

            // Cargo
            jComboBox_cargo.removeAllItems();
            jComboBox_cargo.addItem("-- Seleccionar --");
            ResultSet rsCargo = conexionBD.cargarComboCargo();
            while (rsCargo.next()) {
                jComboBox_cargo.addItem(rsCargo.getInt("id_cargo") + " - " + rsCargo.getString("nombre_cargo"));
            }

            // Area
            jComboBox_area.removeAllItems();
            jComboBox_area.addItem("-- Seleccionar --");
            ResultSet rsArea = conexionBD.cargarComboArea();
            while (rsArea.next()) {
                jComboBox_area.addItem(rsArea.getInt("id_area") + " - " + rsArea.getString("nombre_area"));
            }

            // Sucursal
            jComboBox_sucursal.removeAllItems();
            jComboBox_sucursal.addItem("-- Seleccionar --");
            ResultSet rsSucursal = conexionBD.cargarComboSucursal();
            while (rsSucursal.next()) {
                jComboBox_sucursal.addItem(rsSucursal.getInt("id_sucursal") + " - " + rsSucursal.getString("nombre"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar listas desplegables: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_documento = new javax.swing.JTextField();
        txt_personal = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_sucursal = new javax.swing.JComboBox<>();
        jComboBox_personal = new javax.swing.JComboBox<>();
        jComboBox_cargo = new javax.swing.JComboBox<>();
        jComboBox_area = new javax.swing.JComboBox<>();
        BTN_VerPersonal = new javax.swing.JButton();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TXT_BuscarPersonal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableman_personal = new javax.swing.JTable();
        BTN_PDF = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        BTN_Cerrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MANTENIMIENTO DE PERSONAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID Personal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setText("Documento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setText("Nombres");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setText("Apellidos");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel2.add(txt_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 120, 30));

        txt_personal.addActionListener(this::txt_personalActionPerformed);
        jPanel2.add(txt_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 120, 30));
        jPanel2.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, 30));
        jPanel2.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, 30));

        jLabel6.setText("Sucursal");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel7.setText("Tipo Personal");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel8.setText("Cargo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel9.setText("Area");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jComboBox_sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 180, 30));

        jComboBox_personal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 12, 180, 30));

        jComboBox_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 180, 30));

        jComboBox_area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 180, 30));

        BTN_VerPersonal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_VerPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        BTN_VerPersonal.setText("VER PERSONAL");
        BTN_VerPersonal.addActionListener(this::BTN_VerPersonalActionPerformed);
        jPanel2.add(BTN_VerPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 180, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 850, 220));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        jPanel1.add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible (1).png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        jPanel1.add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 190, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ahorrar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        jPanel1.add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 200, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingresar el Nombre de Inventario");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        TXT_BuscarPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarPersonalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarPersonalKeyTyped(evt);
            }
        });
        jPanel3.add(TXT_BuscarPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel11.setText("BUSCAR");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 810, 50));

        jTableman_personal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableman_personal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableman_personalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableman_personal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 810, 250));

        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-de-acrobat-reader.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        jPanel1.add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, 120, 40));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        jPanel1.add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, 120, 40));

        BTN_Cerrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrado.png"))); // NOI18N
        BTN_Cerrar1.setText("Cerrar");
        BTN_Cerrar1.addActionListener(this::BTN_Cerrar1ActionPerformed);
        jPanel1.add(BTN_Cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_personalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_personalActionPerformed

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
        LimpiarCajas();
        BTN_Guardar.setEnabled(true);
        BTN_Modificar.setEnabled(false);
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
        if (jComboBox_personal.getSelectedIndex() == 0 || jComboBox_cargo.getSelectedIndex() == 0 ||
            jComboBox_area.getSelectedIndex() == 0 || jComboBox_sucursal.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar las opciones de Tipo Personal, Cargo, Área y Sucursal.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txt_nombre.getText().trim().isEmpty() || txt_apellidos.getText().trim().isEmpty() || txt_documento.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int idTipo = Integer.parseInt(jComboBox_personal.getSelectedItem().toString().split(" - ")[0]);
            int idCargo = Integer.parseInt(jComboBox_cargo.getSelectedItem().toString().split(" - ")[0]);
            int idArea = Integer.parseInt(jComboBox_area.getSelectedItem().toString().split(" - ")[0]);
            int idSucursal = Integer.parseInt(jComboBox_sucursal.getSelectedItem().toString().split(" - ")[0]);

            conexionBD.insertarPersonal(
                idTipo, idCargo, idArea, idSucursal,
                txt_nombre.getText().trim(),
                txt_apellidos.getText().trim(),
                txt_documento.getText().trim()
            );

            JOptionPane.showMessageDialog(this, "Personal registrado exitosamente.");
            MostrarPersonal();
            LimpiarCajas();
            BTN_Guardar.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
        if (txt_personal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla para modificar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int idPersonal = Integer.parseInt(txt_personal.getText());
            int idTipo = Integer.parseInt(jComboBox_personal.getSelectedItem().toString().split(" - ")[0]);
            int idCargo = Integer.parseInt(jComboBox_cargo.getSelectedItem().toString().split(" - ")[0]);
            int idArea = Integer.parseInt(jComboBox_area.getSelectedItem().toString().split(" - ")[0]);
            int idSucursal = Integer.parseInt(jComboBox_sucursal.getSelectedItem().toString().split(" - ")[0]);

            conexionBD.modificarPersonal(
                idPersonal, idTipo, idCargo, idArea, idSucursal,
                txt_nombre.getText().trim(),
                txt_apellidos.getText().trim(),
                txt_documento.getText().trim()
            );

            JOptionPane.showMessageDialog(this, "Registro de personal modificado exitosamente.");
            MostrarPersonal();
            LimpiarCajas();
            BTN_Modificar.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void TXT_BuscarPersonalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarPersonalKeyReleased
        String filtro = TXT_BuscarPersonal.getText().trim();
        modeloTablaPersonal.setRowCount(0);
        try {
            ResultSet rs = conexionBD.buscarPersonal(filtro);
            while (rs.next()) {
                Object row[] = new Object[12];
                row[0] = rs.getInt("id_personal");
                row[1] = rs.getInt("id_tipo_personal");
                row[2] = rs.getString("nombre_tipo_personal");
                row[3] = rs.getInt("id_cargo");
                row[4] = rs.getString("nombre_cargo");
                row[5] = rs.getInt("id_area");
                row[6] = rs.getString("nombre_area");
                row[7] = rs.getInt("id_sucursal");
                row[8] = rs.getString("nombre_sucursal");
                row[9] = rs.getString("nombres");
                row[10] = rs.getString("apellidos");
                row[11] = rs.getString("documento");
                modeloTablaPersonal.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en la búsqueda: " + e.getMessage());
        }
    }//GEN-LAST:event_TXT_BuscarPersonalKeyReleased

    private void TXT_BuscarPersonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarPersonalKeyTyped

    }//GEN-LAST:event_TXT_BuscarPersonalKeyTyped

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void BTN_Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Cerrar1ActionPerformed
       int opcion = JOptionPane.showConfirmDialog(
            this, 
            "¿Esta seguro de cerrar la ventana?", 
            "Confirmar salida", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_BTN_Cerrar1ActionPerformed

    private void BTN_VerPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VerPersonalActionPerformed
    MostrarPersonal();
    }//GEN-LAST:event_BTN_VerPersonalActionPerformed

    private void jTableman_personalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableman_personalMouseClicked
        int fila = jTableman_personal.getSelectedRow();
        if (fila >= 0) {
            txt_personal.setText(jTableman_personal.getValueAt(fila, 0).toString());

            // Seleccionar tipo de personal
            String idTipo = jTableman_personal.getValueAt(fila, 1).toString();
            for (int i = 0; i < jComboBox_personal.getItemCount(); i++) {
                if (jComboBox_personal.getItemAt(i).startsWith(idTipo + " - ")) {
                    jComboBox_personal.setSelectedIndex(i);
                    break;
                }
            }

            // Seleccionar cargo
            String idCargo = jTableman_personal.getValueAt(fila, 3).toString();
            for (int i = 0; i < jComboBox_cargo.getItemCount(); i++) {
                if (jComboBox_cargo.getItemAt(i).startsWith(idCargo + " - ")) {
                    jComboBox_cargo.setSelectedIndex(i);
                    break;
                }
            }

            // Seleccionar área
            String idArea = jTableman_personal.getValueAt(fila, 5).toString();
            for (int i = 0; i < jComboBox_area.getItemCount(); i++) {
                if (jComboBox_area.getItemAt(i).startsWith(idArea + " - ")) {
                    jComboBox_area.setSelectedIndex(i);
                    break;
                }
            }

            // Seleccionar sucursal
            String idSucursal = jTableman_personal.getValueAt(fila, 7).toString();
            for (int i = 0; i < jComboBox_sucursal.getItemCount(); i++) {
                if (jComboBox_sucursal.getItemAt(i).startsWith(idSucursal + " - ")) {
                    jComboBox_sucursal.setSelectedIndex(i);
                    break;
                }
            }

            txt_nombre.setText(jTableman_personal.getValueAt(fila, 9).toString());
            txt_apellidos.setText(jTableman_personal.getValueAt(fila, 10).toString());
            txt_documento.setText(jTableman_personal.getValueAt(fila, 11).toString());

            BTN_Guardar.setEnabled(false);
            BTN_Modificar.setEnabled(true);
        }
    }//GEN-LAST:event_jTableman_personalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_personal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar1;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_VerPersonal;
    private javax.swing.JTextField TXT_BuscarPersonal;
    private javax.swing.JComboBox<String> jComboBox_area;
    private javax.swing.JComboBox<String> jComboBox_cargo;
    private javax.swing.JComboBox<String> jComboBox_personal;
    private javax.swing.JComboBox<String> jComboBox_sucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableman_personal;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_documento;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_personal;
    // End of variables declaration//GEN-END:variables
public void MostrarPersonal() {
        modeloTablaPersonal.setRowCount(0);
        try {
            ResultSet rs = conexionBD.listarPersonal();
            while (rs.next()) {
                Object row[] = new Object[12];
                row[0] = rs.getInt("id_personal");
                row[1] = rs.getInt("id_tipo_personal");
                row[2] = rs.getString("nombre_tipo_personal");
                row[3] = rs.getInt("id_cargo");
                row[4] = rs.getString("nombre_cargo");
                row[5] = rs.getInt("id_area");
                row[6] = rs.getString("nombre_area");
                row[7] = rs.getInt("id_sucursal");
                row[8] = rs.getString("nombre_sucursal");
                row[9] = rs.getString("nombres");
                row[10] = rs.getString("apellidos");
                row[11] = rs.getString("documento");
                modeloTablaPersonal.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al listar el personal: " + e.getMessage());
        }
    }

    public void LimpiarCajas() {
        txt_personal.setText("");
        txt_nombre.setText("");
        txt_apellidos.setText("");
        txt_documento.setText("");
        jComboBox_personal.setSelectedIndex(0);
        jComboBox_cargo.setSelectedIndex(0);
        jComboBox_area.setSelectedIndex(0);
        jComboBox_sucursal.setSelectedIndex(0);
    }
}
