
package proyecto_almacen;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_cliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_cliente.class.getName());
/* Modelo para mostrar datos en la tabla */
    DefaultTableModel modeloTablaCliente = new DefaultTableModel();

    /* Objeto de conexión a la base de datos */
    conexionBD_gabriel conexionBD;
    
    
    public frm_cliente() {
        setUndecorated(true);
        initComponents();
        txtcodigocliente.setEnabled(false);
        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
                
        setLocationRelativeTo(null);


        // Crear la conexión al iniciar el formulario
        conexionBD = new conexionBD_gabriel();

        // Verificar que la conexión fue exitosa
        if (conexionBD.getConnection() == null) {
            JOptionPane.showMessageDialog(null, "No se pudo conectar con la base de datos.",
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            return; // Evita continuar si no hay conexión
        }

        // Definir los encabezados de la tabla
        String titulos[] = {"Codigo cliente", "Nombre cliente", "Direccion", "Telefono", "Correo"};

        // Asignar los títulos al modelo
        modeloTablaCliente.setColumnIdentifiers(titulos);

        // Establecer el modelo a la JTable
        JTABLE_Mant_cliente.setModel(modeloTablaCliente);

        // Deshabilitar campo de código (solo lo mostrará, no se escribe)
        txtcodigocliente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        BTN_VerCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtnombrecliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcodigocliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mant_cliente = new javax.swing.JTable();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXT_BuscarCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTN_Cerrar1 = new javax.swing.JButton();
        BTN_PDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("MANTENIMIENTO DE CLIENTES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 240, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Correo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre Cliente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(0, 0, 204));
        txtcorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 220, 30));

        txtdireccion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 0, 204));
        txtdireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 260, 30));

        BTN_VerCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_VerCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        BTN_VerCliente.setText("VER CLIENTE");
        BTN_VerCliente.addActionListener(this::BTN_VerClienteActionPerformed);
        jPanel1.add(BTN_VerCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 180, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("CodigoCliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtnombrecliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnombrecliente.setForeground(new java.awt.Color(0, 0, 204));
        txtnombrecliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombrecliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnombrecliente.addActionListener(this::txtnombreclienteActionPerformed);
        txtnombrecliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreclienteKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 59, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtcodigocliente.setEditable(false);
        txtcodigocliente.setBackground(new java.awt.Color(255, 255, 255));
        txtcodigocliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcodigocliente.setForeground(new java.awt.Color(0, 0, 204));
        txtcodigocliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigocliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtcodigocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefono");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        txt_telefono.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(0, 0, 204));
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 820, 140));

        JTABLE_Mant_cliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mant_cliente.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mant_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTABLE_Mant_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_Mant_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mant_cliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 810, 220));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        getContentPane().add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible (1).png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        getContentPane().add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 190, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ahorrar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        getContentPane().add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 200, 50));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        getContentPane().add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 120, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresar el Nombre del cliente");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        TXT_BuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarClienteKeyTyped(evt);
            }
        });
        jPanel2.add(TXT_BuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel5.setText("BUSCAR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 810, 50));

        BTN_Cerrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrado.png"))); // NOI18N
        BTN_Cerrar1.setText("Cerrar");
        BTN_Cerrar1.addActionListener(this::BTN_Cerrar1ActionPerformed);
        getContentPane().add(BTN_Cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 130, 40));

        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-de-acrobat-reader.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        getContentPane().add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped

    }//GEN-LAST:event_txtdireccionKeyTyped

    private void BTN_VerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VerClienteActionPerformed
 this.MostrarClientes();
    }//GEN-LAST:event_BTN_VerClienteActionPerformed

    private void JTABLE_Mant_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_Mant_clienteMouseClicked
int filaSeleccionada = JTABLE_Mant_cliente.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String codigo = JTABLE_Mant_cliente.getValueAt(filaSeleccionada, 0).toString();
            String nombre = JTABLE_Mant_cliente.getValueAt(filaSeleccionada, 1).toString();
            String direccion = JTABLE_Mant_cliente.getValueAt(filaSeleccionada, 2) != null ? JTABLE_Mant_cliente.getValueAt(filaSeleccionada, 2).toString() : "";
            String telefono = JTABLE_Mant_cliente.getValueAt(filaSeleccionada, 3) != null ? JTABLE_Mant_cliente.getValueAt(filaSeleccionada, 3).toString() : "";
            String correo = JTABLE_Mant_cliente.getValueAt(filaSeleccionada, 4) != null ? JTABLE_Mant_cliente.getValueAt(filaSeleccionada, 4).toString() : "";

            txtcodigocliente.setText(codigo);
            txtnombrecliente.setText(nombre);
            txtdireccion.setText(direccion);
            txt_telefono.setText(telefono);
            txtcorreo.setText(correo);

            txtnombrecliente.setEnabled(true);
            BTN_Modificar.setEnabled(true);
            BTN_Guardar.setEnabled(false);
        }
    }//GEN-LAST:event_JTABLE_Mant_clienteMouseClicked

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
txtcodigocliente.setText("");
        txtnombrecliente.setText("");
        txtdireccion.setText("");
        txt_telefono.setText("");
        txtcorreo.setText("");

        txtnombrecliente.requestFocus();
        txtnombrecliente.setEnabled(true);

        BTN_Guardar.setEnabled(true);
        BTN_Modificar.setEnabled(false);
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
String nombreCliente = txtnombrecliente.getText().trim();
        String direccion = txtdireccion.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String correo = txtcorreo.getText().trim();

        if (nombreCliente.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos del Cliente",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            txtnombrecliente.requestFocus();
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea guardar el registro del Cliente?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.insertarCliente(nombreCliente, direccion, telefono, correo);

                JOptionPane.showMessageDialog(null, "Cliente registrado correctamente",
                        "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarClientes();

                txtcodigocliente.setText("");
                txtnombrecliente.setText("");
                txtdireccion.setText("");
                txt_telefono.setText("");
                txtcorreo.setText("");
                BTN_Guardar.setEnabled(false);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al registrar Cliente:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
String codStr = txtcodigocliente.getText().trim();
        String nombreCliente = txtnombrecliente.getText().trim();
        String direccion = txtdireccion.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String correo = txtcorreo.getText().trim();

        if (codStr.isEmpty() || nombreCliente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente de la tabla y complete el Nombre",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = Integer.parseInt(codStr);

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea modificar este cliente?", "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.modificarCliente(codigo, nombreCliente, direccion, telefono, correo);

                JOptionPane.showMessageDialog(null, "Cliente modificado correctamente",
                        "Modificación exitosa", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarClientes();

                txtcodigocliente.setText("");
                txtnombrecliente.setText("");
                txtdireccion.setText("");
                txt_telefono.setText("");
                txtcorreo.setText("");
                BTN_Modificar.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al modificar cliente:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void TXT_BuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarClienteKeyReleased
this.buscarClientes();
    }//GEN-LAST:event_TXT_BuscarClienteKeyReleased

    private void TXT_BuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarClienteKeyTyped

    }//GEN-LAST:event_TXT_BuscarClienteKeyTyped

    private void BTN_Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Cerrar1ActionPerformed
int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas cerrar el formulario?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                conexionBD.cerrarConexion();
            } catch (Exception e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
            dispose();
        }
    }//GEN-LAST:event_BTN_Cerrar1ActionPerformed

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void txtnombreclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreclienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreclienteKeyTyped

    private void txtnombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_cliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar1;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_VerCliente;
    private javax.swing.JTable JTABLE_Mant_cliente;
    private javax.swing.JTextField TXT_BuscarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txtcodigocliente;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombrecliente;
    // End of variables declaration//GEN-END:variables
public void MostrarClientes() {
        txtnombrecliente.setEnabled(true);
        JTABLE_Mant_cliente.setAutoCreateRowSorter(true);
        modeloTablaCliente.setRowCount(0);
        try {
            ResultSet rs = conexionBD.listarClientes();
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_cliente"),
                    rs.getString("nombre_cliente"),
                    rs.getString("direccion"),
                    rs.getString("telefono"),
                    rs.getString("correo")
                };
                modeloTablaCliente.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Cliente:\n" + e.getMessage(),
                    "Error de consulta", JOptionPane.ERROR_MESSAGE);
        }
    }
public void buscarClientes() {
        modeloTablaCliente.setRowCount(0);
        String busqueda = TXT_BuscarCliente.getText().trim();
        try {
            ResultSet rs = conexionBD.buscarClientes(busqueda);
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_cliente"),
                    rs.getString("nombre_cliente"),
                    rs.getString("direccion"),
                    rs.getString("telefono"),
                    rs.getString("correo")
                };
                modeloTablaCliente.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Error al buscar Clientes:\n" + e.getMessage(),
                    "Error de búsqueda", JOptionPane.ERROR_MESSAGE);
        }
    }
}
