
package proyecto_almacen;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_almacen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_almacen.class.getName());
 /* Modelo para mostrar datos en la tabla */
    DefaultTableModel modeloTablaAlmacen = new DefaultTableModel();

    /* Objeto de conexión a la base de datos */
    conexionBD_gabriel conexionBD;
    
    public frm_almacen() {
        setUndecorated(true);
        initComponents();
        txtcodigo_almacen2.setEnabled(false);
        txtnombre_almacen.setEditable(true);
        txtubicacion1.setEditable(true);
        jComboBox1_sucursal.setEnabled(true);
        
        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        BTN_Dardebaja.setEnabled(false);
        
        setLocationRelativeTo(null);

        // Crear la conexión al iniciar el formulario
        conexionBD = new conexionBD_gabriel();

        // Verificar que la conexión fue exitosa
        if (conexionBD.getConnection() == null) {
            JOptionPane.showMessageDialog(null, "No se pudo conectar con la base de datos.",
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            return; // Evita continuar si no hay conexión
        }

        // Cargar las sucursales en el JComboBox
        this.cargarSucursales();

        // Definir los encabezados de la tabla
        String titulos[] = {"Codigo", "ID Sucursal", "Sucursal", "Nombre Almacen", "Ubicacion"};

        // Asignar los títulos al modelo
        modeloTablaAlmacen.setColumnIdentifiers(titulos);

        // Establecer el modelo a la JTable
        JTABLE_Mant_almacen.setModel(modeloTablaAlmacen);

        // Ocultar la columna id_sucursal (índice 1) para mantener limpia la interfaz
        JTABLE_Mant_almacen.getColumnModel().getColumn(1).setMinWidth(0);
        JTABLE_Mant_almacen.getColumnModel().getColumn(1).setMaxWidth(0);
        JTABLE_Mant_almacen.getColumnModel().getColumn(1).setWidth(0);

        // Deshabilitar campo de código (solo lo mostrará, no se escribe)
        txtcodigo_almacen2.setEnabled(false);
    }

    /* Método para llenar el JComboBox con las sucursales */
    private void cargarSucursales() {
        jComboBox1_sucursal.removeAllItems();
        jComboBox1_sucursal.addItem("-- Seleccionar --");
        try {
            String sql = "SELECT id_sucursal, nombre FROM sucursal";
            Statement st = conexionBD.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                jComboBox1_sucursal.addItem(rs.getInt("id_sucursal") + " - " + rs.getString("nombre"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar sucursales:\n" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /* Método auxiliar para obtener el ID de la sucursal seleccionada en el ComboBox */
    private int obtenerIdSucursalSeleccionada() {
        if (jComboBox1_sucursal.getSelectedIndex() <= 0) {
            return 0;
        }
        String item = jComboBox1_sucursal.getSelectedItem().toString();
        String[] partes = item.split(" - ");
        return Integer.parseInt(partes[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre_almacen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1_sucursal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigo_almacen2 = new javax.swing.JTextField();
        txtubicacion1 = new javax.swing.JTextField();
        BTN_VerAlmacen = new javax.swing.JButton();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Dardebaja = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TXT_BuscarAlmacen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mant_almacen = new javax.swing.JTable();
        BTN_PDF = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        BTN_Cerrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MANTENIMIENTO DE ALMACEN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Sucursal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        txtnombre_almacen.setEditable(false);
        txtnombre_almacen.setBackground(new java.awt.Color(255, 255, 255));
        txtnombre_almacen.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnombre_almacen.setForeground(new java.awt.Color(0, 0, 204));
        txtnombre_almacen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombre_almacen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnombre_almacen.addActionListener(this::txtnombre_almacenActionPerformed);
        jPanel2.add(txtnombre_almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 130, 30));

        jLabel3.setText("Codigo Almacen");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBox1_sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 190, -1));

        jLabel4.setText("Nombre Almacen");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setText("Ubicacion");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        txtcodigo_almacen2.setEditable(false);
        txtcodigo_almacen2.setBackground(new java.awt.Color(255, 255, 255));
        txtcodigo_almacen2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcodigo_almacen2.setForeground(new java.awt.Color(0, 0, 204));
        txtcodigo_almacen2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigo_almacen2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtcodigo_almacen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, 30));

        txtubicacion1.setEditable(false);
        txtubicacion1.setBackground(new java.awt.Color(255, 255, 255));
        txtubicacion1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtubicacion1.setForeground(new java.awt.Color(0, 0, 204));
        txtubicacion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtubicacion1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtubicacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 210, 30));

        BTN_VerAlmacen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_VerAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        BTN_VerAlmacen.setText("VER ALMACEN");
        BTN_VerAlmacen.addActionListener(this::BTN_VerAlmacenActionPerformed);
        jPanel2.add(BTN_VerAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 180, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 830, 110));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        jPanel1.add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible (1).png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        jPanel1.add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 190, 50));

        BTN_Dardebaja.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Dardebaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/expediente.png"))); // NOI18N
        BTN_Dardebaja.setText("Dar de baja");
        BTN_Dardebaja.addActionListener(this::BTN_DardebajaActionPerformed);
        jPanel1.add(BTN_Dardebaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 180, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ahorrar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        jPanel1.add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 200, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingresar el Nombre de Almacen");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        TXT_BuscarAlmacen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarAlmacenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarAlmacenKeyTyped(evt);
            }
        });
        jPanel3.add(TXT_BuscarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel7.setText("BUSCAR");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 810, 50));

        JTABLE_Mant_almacen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mant_almacen.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mant_almacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTABLE_Mant_almacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_Mant_almacenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mant_almacen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 810, 220));

        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-de-acrobat-reader.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        jPanel1.add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 120, 40));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        jPanel1.add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 120, 40));

        BTN_Cerrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrado.png"))); // NOI18N
        BTN_Cerrar1.setText("Cerrar");
        BTN_Cerrar1.addActionListener(this::BTN_Cerrar1ActionPerformed);
        jPanel1.add(BTN_Cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombre_almacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombre_almacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombre_almacenActionPerformed

    private void BTN_VerAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VerAlmacenActionPerformed
       this.MostrarAlmacenes();
    }//GEN-LAST:event_BTN_VerAlmacenActionPerformed

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
      txtcodigo_almacen2.setText("");
        txtnombre_almacen.setText("");
        txtubicacion1.setText("");
        if (jComboBox1_sucursal.getItemCount() > 0) {
            jComboBox1_sucursal.setSelectedIndex(0);
        }

        txtnombre_almacen.requestFocus();
        
        BTN_Guardar.setEnabled(true);
        BTN_Modificar.setEnabled(false);
        BTN_Dardebaja.setEnabled(false);
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
        int idSucursal = obtenerIdSucursalSeleccionada();
        String nombre = txtnombre_almacen.getText().trim();
        String ubicacion = txtubicacion1.getText().trim();

        if (idSucursal == 0 || nombre.isEmpty() || ubicacion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos requeridos.",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea guardar el registro del Almacén?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.insertarAlmacen(idSucursal, nombre, ubicacion);

                JOptionPane.showMessageDialog(null, "Almacén registrado correctamente",
                        "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarAlmacenes();

                txtcodigo_almacen2.setText("");
                txtnombre_almacen.setText("");
                txtubicacion1.setText("");
                jComboBox1_sucursal.setSelectedIndex(0);
                
                BTN_Guardar.setEnabled(false);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al registrar Almacén:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_DardebajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DardebajaActionPerformed
       String codStr = txtcodigo_almacen2.getText().trim();

        if (codStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un almacén de la tabla para dar de baja.",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = Integer.parseInt(codStr);

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea dar de baja este almacén?", "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.desactivarAlmacen(codigo);

                JOptionPane.showMessageDialog(null, "Almacén dado de baja correctamente",
                        "Desactivación exitosa", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarAlmacenes();

                txtcodigo_almacen2.setText("");
                txtnombre_almacen.setText("");
                txtubicacion1.setText("");
                jComboBox1_sucursal.setSelectedIndex(0);
                
                BTN_Modificar.setEnabled(false);
                BTN_Dardebaja.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al dar de baja el almacén:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_DardebajaActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
        String codStr = txtcodigo_almacen2.getText().trim();
        int idSucursal = obtenerIdSucursalSeleccionada();
        String nombre = txtnombre_almacen.getText().trim();
        String ubicacion = txtubicacion1.getText().trim();

        if (codStr.isEmpty() || idSucursal == 0 || nombre.isEmpty() || ubicacion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un almacén de la tabla y complete todos los campos.",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = Integer.parseInt(codStr);

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea modificar este almacén?", "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.modificarAlmacen(codigo, idSucursal, nombre, ubicacion);

                JOptionPane.showMessageDialog(null, "Almacén modificado correctamente",
                        "Modificación exitosa", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarAlmacenes();

                txtcodigo_almacen2.setText("");
                txtnombre_almacen.setText("");
                txtubicacion1.setText("");
                jComboBox1_sucursal.setSelectedIndex(0);
                
                BTN_Modificar.setEnabled(false);
                BTN_Dardebaja.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al modificar almacén:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void TXT_BuscarAlmacenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarAlmacenKeyReleased
        this.buscarAlmacenes();
    }//GEN-LAST:event_TXT_BuscarAlmacenKeyReleased

    private void TXT_BuscarAlmacenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarAlmacenKeyTyped

    }//GEN-LAST:event_TXT_BuscarAlmacenKeyTyped

    private void JTABLE_Mant_almacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_Mant_almacenMouseClicked
       int filaSeleccionada = JTABLE_Mant_almacen.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String codigo = JTABLE_Mant_almacen.getValueAt(filaSeleccionada, 0).toString();
            int idSucursal = Integer.parseInt(JTABLE_Mant_almacen.getValueAt(filaSeleccionada, 1).toString());
            String nombre = JTABLE_Mant_almacen.getValueAt(filaSeleccionada, 3) != null ? JTABLE_Mant_almacen.getValueAt(filaSeleccionada, 3).toString() : "";
            String ubicacion = JTABLE_Mant_almacen.getValueAt(filaSeleccionada, 4) != null ? JTABLE_Mant_almacen.getValueAt(filaSeleccionada, 4).toString() : "";

            txtcodigo_almacen2.setText(codigo);
            txtnombre_almacen.setText(nombre);
            txtubicacion1.setText(ubicacion);

            // Seleccionar en el JComboBox la sucursal correspondiente por ID
            for (int i = 0; i < jComboBox1_sucursal.getItemCount(); i++) {
                String item = jComboBox1_sucursal.getItemAt(i);
                if (item.startsWith(idSucursal + " - ")) {
                    jComboBox1_sucursal.setSelectedIndex(i);
                    break;
                }
            }

            BTN_Modificar.setEnabled(true);
            BTN_Dardebaja.setEnabled(true);
            BTN_Guardar.setEnabled(false);
        }
    }//GEN-LAST:event_JTABLE_Mant_almacenMouseClicked

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void BTN_Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Cerrar1ActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas cerrar el formulario?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                conexionBD.cerrarConexion();
            } catch (Exception e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
            dispose();
        }
    }//GEN-LAST:event_BTN_Cerrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_almacen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar1;
    private javax.swing.JButton BTN_Dardebaja;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_VerAlmacen;
    private javax.swing.JTable JTABLE_Mant_almacen;
    private javax.swing.JTextField TXT_BuscarAlmacen;
    private javax.swing.JComboBox<String> jComboBox1_sucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcodigo_almacen2;
    private javax.swing.JTextField txtnombre_almacen;
    private javax.swing.JTextField txtubicacion1;
    // End of variables declaration//GEN-END:variables
public void MostrarAlmacenes() {
        JTABLE_Mant_almacen.setAutoCreateRowSorter(true);
        modeloTablaAlmacen.setRowCount(0);
        try {
            ResultSet rs = conexionBD.listarAlmacenes();
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_almacen"),
                    rs.getInt("id_sucursal"),
                    rs.getString("nombre_sucursal"),
                    rs.getString("nombre_almacen"),
                    rs.getString("ubicacion")
                };
                modeloTablaAlmacen.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Almacenes:\n" + e.getMessage(),
                    "Error de consulta", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void buscarAlmacenes() {
        modeloTablaAlmacen.setRowCount(0);
        String busqueda = TXT_BuscarAlmacen.getText().trim();
        try {
            ResultSet rs = conexionBD.buscarAlmacenes(busqueda);
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_almacen"),
                    rs.getInt("id_sucursal"),
                    rs.getString("nombre_sucursal"),
                    rs.getString("nombre_almacen"),
                    rs.getString("ubicacion")
                };
                modeloTablaAlmacen.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Error al buscar Almacenes:\n" + e.getMessage(),
                    "Error de búsqueda", JOptionPane.ERROR_MESSAGE);
        }
    }
}
