
package proyecto_almacen;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_proveedor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_proveedor.class.getName());
    /* Modelo para mostrar datos en la tabla */
    DefaultTableModel modeloTablaProveedor = new DefaultTableModel();

    /* Objeto de conexión a la base de datos */
    conexionBD_gabriel conexionBD;
    
    public frm_proveedor() {
        setUndecorated(true);
        initComponents();
        txtcodigoproveedor1.setEnabled(false);
        txt_telefono.setEditable(true);
        txtcorreo.setEditable(true);
        txtdireccion.setEditable(true);
        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        
        setLocationRelativeTo(null);

        
        // Crear la conexión al iniciar el formulario
        conexionBD = new conexionBD_gabriel();

        // Verificar que la conexión fue exitosa
        if (conexionBD.getConnection() == null) {
            JOptionPane.showMessageDialog(null, "No se pudo conectar con la base de datos.",
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            return; // Evita continuar si no hay conexión
        }

        // Definir los encabezados de la tabla
        String titulos[] = {"Codigo", "RUC", "Nombre / Razon Social", "Telefono", "Correo", "Direccion"};

        // Asignar los títulos al modelo
        modeloTablaProveedor.setColumnIdentifiers(titulos);

        // Establecer el modelo a la JTable
        JTABLE_Mant_Proveedor.setModel(modeloTablaProveedor);

        // Deshabilitar campo de código (solo lo mostrará, no se escribe)
        txtcodigoproveedor1.setEnabled(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txtruc = new javax.swing.JTextField();
        BTN_VerProveedor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtnombreproveedor1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcodigoproveedor1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mant_Proveedor = new javax.swing.JTable();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXT_BuscarProveedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTN_Cerrar1 = new javax.swing.JButton();
        BTN_PDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("MANTENIMIENTO DE PROVEEDOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 240, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Direccion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ruc");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtdireccion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtdireccion.setForeground(new java.awt.Color(0, 0, 204));
        txtdireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, 30));

        txtruc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtruc.setForeground(new java.awt.Color(0, 0, 204));
        txtruc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtruc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrucKeyTyped(evt);
            }
        });
        jPanel1.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, 30));

        BTN_VerProveedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_VerProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        BTN_VerProveedor.setText("VER PROVEEDORES");
        BTN_VerProveedor.addActionListener(this::BTN_VerProveedorActionPerformed);
        jPanel1.add(BTN_VerProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 180, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nombre Proveedor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtnombreproveedor1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnombreproveedor1.setForeground(new java.awt.Color(0, 0, 204));
        txtnombreproveedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombreproveedor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnombreproveedor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreproveedor1KeyTyped(evt);
            }
        });
        jPanel1.add(txtnombreproveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 59, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Codigo Proveedor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtcodigoproveedor1.setEditable(false);
        txtcodigoproveedor1.setBackground(new java.awt.Color(255, 255, 255));
        txtcodigoproveedor1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcodigoproveedor1.setForeground(new java.awt.Color(0, 0, 204));
        txtcodigoproveedor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigoproveedor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtcodigoproveedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefono");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        txt_telefono.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(0, 0, 204));
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Correo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        txtcorreo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(0, 0, 204));
        txtcorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 790, 140));

        JTABLE_Mant_Proveedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mant_Proveedor.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mant_Proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTABLE_Mant_Proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_Mant_ProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mant_Proveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 810, 220));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        getContentPane().add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible (1).png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        getContentPane().add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 190, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ahorrar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        getContentPane().add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 200, 50));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        getContentPane().add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 120, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresar el Nombre del proveedor");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        TXT_BuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarProveedorKeyTyped(evt);
            }
        });
        jPanel2.add(TXT_BuscarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel5.setText("BUSCAR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 810, 50));

        BTN_Cerrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrado.png"))); // NOI18N
        BTN_Cerrar1.setText("Cerrar");
        BTN_Cerrar1.addActionListener(this::BTN_Cerrar1ActionPerformed);
        getContentPane().add(BTN_Cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 130, 40));

        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-de-acrobat-reader.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        getContentPane().add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyTyped

    }//GEN-LAST:event_txtrucKeyTyped

    private void BTN_VerProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VerProveedorActionPerformed
this.MostrarProveedores();
    }//GEN-LAST:event_BTN_VerProveedorActionPerformed

    private void JTABLE_Mant_ProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_Mant_ProveedorMouseClicked
int filaSeleccionada = JTABLE_Mant_Proveedor.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String codigo = JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 0).toString();
            String ruc = JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 1) != null ? JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 1).toString() : "";
            String nombre = JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 2) != null ? JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 2).toString() : "";
            String telefono = JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 3) != null ? JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 3).toString() : "";
            String correo = JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 4) != null ? JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 4).toString() : "";
            String direccion = JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 5) != null ? JTABLE_Mant_Proveedor.getValueAt(filaSeleccionada, 5).toString() : "";

            txtcodigoproveedor1.setText(codigo);
            txtruc.setText(ruc);
            txtnombreproveedor1.setText(nombre);
            txt_telefono.setText(telefono);
            txtcorreo.setText(correo);
            txtdireccion.setText(direccion);

            txtnombreproveedor1.setEnabled(true);
            BTN_Modificar.setEnabled(true);
            BTN_Guardar.setEnabled(false);
        }
    }//GEN-LAST:event_JTABLE_Mant_ProveedorMouseClicked

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
txtcodigoproveedor1.setText("");
        txtruc.setText("");
        txtnombreproveedor1.setText("");
        txt_telefono.setText("");
        txtcorreo.setText("");
        txtdireccion.setText("");

        txtruc.requestFocus();
        txtnombreproveedor1.setEnabled(true);

        BTN_Guardar.setEnabled(true);
        BTN_Modificar.setEnabled(false);
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
String ruc = txtruc.getText().trim();
        String nombre = txtnombreproveedor1.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String correo = txtcorreo.getText().trim();
        String direccion = txtdireccion.getText().trim();

        if (ruc.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete al menos el RUC y el Nombre del Proveedor",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            txtruc.requestFocus();
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea guardar el registro del Proveedor?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.insertarProveedor(ruc, nombre, telefono, correo, direccion);

                JOptionPane.showMessageDialog(null, "Proveedor registrado correctamente",
                        "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarProveedores();

                txtcodigoproveedor1.setText("");
                txtruc.setText("");
                txtnombreproveedor1.setText("");
                txt_telefono.setText("");
                txtcorreo.setText("");
                txtdireccion.setText("");
                BTN_Guardar.setEnabled(false);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al registrar Proveedor:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
String codStr = txtcodigoproveedor1.getText().trim();
        String ruc = txtruc.getText().trim();
        String nombre = txtnombreproveedor1.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String correo = txtcorreo.getText().trim();
        String direccion = txtdireccion.getText().trim();

        if (codStr.isEmpty() || ruc.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un proveedor de la tabla y complete el RUC y Nombre",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = Integer.parseInt(codStr);

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea modificar este proveedor?", "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.modificarProveedor(codigo, ruc, nombre, telefono, correo, direccion);

                JOptionPane.showMessageDialog(null, "Proveedor modificado correctamente",
                        "Modificación exitosa", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarProveedores();

                txtcodigoproveedor1.setText("");
                txtruc.setText("");
                txtnombreproveedor1.setText("");
                txt_telefono.setText("");
                txtcorreo.setText("");
                txtdireccion.setText("");
                BTN_Modificar.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al modificar proveedor:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void TXT_BuscarProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarProveedorKeyReleased
this.buscarProveedores();
    }//GEN-LAST:event_TXT_BuscarProveedorKeyReleased

    private void TXT_BuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarProveedorKeyTyped

    }//GEN-LAST:event_TXT_BuscarProveedorKeyTyped

    private void BTN_Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Cerrar1ActionPerformed
int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas cerrar el formulario?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                conexionBD.cerrarConexion();
            } catch (Exception e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
            dispose();
        }
    }//GEN-LAST:event_BTN_Cerrar1ActionPerformed

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void txtnombreproveedor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreproveedor1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreproveedor1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_proveedor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar1;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_VerProveedor;
    private javax.swing.JTable JTABLE_Mant_Proveedor;
    private javax.swing.JTextField TXT_BuscarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txtcodigoproveedor1;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombreproveedor1;
    private javax.swing.JTextField txtruc;
    // End of variables declaration//GEN-END:variables
public void MostrarProveedores() {
        txtnombreproveedor1.setEnabled(true);
        JTABLE_Mant_Proveedor.setAutoCreateRowSorter(true);
        modeloTablaProveedor.setRowCount(0);
        try {
            ResultSet rs = conexionBD.listarProveedores();
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_proveedor"),
                    rs.getString("ruc"),
                    rs.getString("nombre"),
                    rs.getString("telefono"),
                    rs.getString("correo"),
                    rs.getString("direccion")
                };
                modeloTablaProveedor.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Proveedor:\n" + e.getMessage(),
                    "Error de consulta", JOptionPane.ERROR_MESSAGE);
        }
    }
public void buscarProveedores() {
        modeloTablaProveedor.setRowCount(0);
        String busqueda = TXT_BuscarProveedor.getText().trim();
        try {
            ResultSet rs = conexionBD.buscarProveedores(busqueda);
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_proveedor"),
                    rs.getString("ruc"),
                    rs.getString("nombre"),
                    rs.getString("telefono"),
                    rs.getString("correo"),
                    rs.getString("direccion")
                };
                modeloTablaProveedor.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Error al buscar Proveedores:\n" + e.getMessage(),
                    "Error de búsqueda", JOptionPane.ERROR_MESSAGE);
        }
    }
}
