
package proyecto_almacen;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_categoria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_categoria.class.getName());
/* Modelo para mostrar datos en la tabla */
    DefaultTableModel modeloTablaCategoria = new DefaultTableModel();
    
    conexionBD_gabriel conexionBD ;
    
    public frm_categoria() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null); // Centrar formulario
        
        txtcodigoCategoria1.setEnabled(false);
        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
                
        setLocationRelativeTo(null);


        // Crear la conexión al iniciar el formulario
        conexionBD = new conexionBD_gabriel();

        // Verificar que la conexión fue exitosa
        if (conexionBD.getConnection() == null) {
            JOptionPane.showMessageDialog(this, "No se pudo conectar con la base de datos.",
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            return; // Evita continuar si no hay conexión
        }
        // Definir los encabezados de la tabla
        String titulos[] = {"Codigo categoria", "Nombre categoria", "Descripcion"};

        // Asignar los títulos al modelo
        modeloTablaCategoria.setColumnIdentifiers(titulos);

        // Establecer el modelo a la JTable
        JTABLE_Mant_Categoria.setModel(modeloTablaCategoria);

        // Deshabilitar campo de código (solo lo mostrará, no se escribe)
        txtcodigoCategoria1.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        txtnombreCategoria = new javax.swing.JTextField();
        BTN_VerCategoria = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtcodigoCategoria1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mant_Categoria = new javax.swing.JTable();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXT_BuscarCategoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTN_Cerrar1 = new javax.swing.JButton();
        BTN_PDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("MANTENIMIENTO DE CATEGORIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 240, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Descripcion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre Categoria");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtdescripcion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(0, 0, 204));
        txtdescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdescripcion.addActionListener(this::txtdescripcionActionPerformed);
        jPanel1.add(txtdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 240, 30));

        txtnombreCategoria.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnombreCategoria.setForeground(new java.awt.Color(0, 0, 204));
        txtnombreCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombreCategoria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnombreCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreCategoriaKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 59, 130, 30));

        BTN_VerCategoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_VerCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        BTN_VerCategoria.setText("VER CATEGORIA");
        BTN_VerCategoria.addActionListener(this::BTN_VerCategoriaActionPerformed);
        jPanel1.add(BTN_VerCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 180, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Codigo Categoria");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtcodigoCategoria1.setEditable(false);
        txtcodigoCategoria1.setBackground(new java.awt.Color(255, 255, 255));
        txtcodigoCategoria1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcodigoCategoria1.setForeground(new java.awt.Color(0, 0, 204));
        txtcodigoCategoria1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigoCategoria1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtcodigoCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 810, 120));

        JTABLE_Mant_Categoria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mant_Categoria.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mant_Categoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTABLE_Mant_Categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_Mant_CategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mant_Categoria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 810, 220));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        getContentPane().add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible (1).png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        getContentPane().add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 190, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ahorrar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        getContentPane().add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 200, 50));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        getContentPane().add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 120, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresar el Nombre de la Categoria");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        TXT_BuscarCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarCategoriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarCategoriaKeyTyped(evt);
            }
        });
        jPanel2.add(TXT_BuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel5.setText("BUSCAR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 810, 50));

        BTN_Cerrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrado.png"))); // NOI18N
        BTN_Cerrar1.setText("Cerrar");
        BTN_Cerrar1.addActionListener(this::BTN_Cerrar1ActionPerformed);
        getContentPane().add(BTN_Cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 130, 40));

        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-de-acrobat-reader.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        getContentPane().add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreCategoriaKeyTyped

    }//GEN-LAST:event_txtnombreCategoriaKeyTyped

    private void BTN_VerCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VerCategoriaActionPerformed
this.mostrarCategorias();
    }//GEN-LAST:event_BTN_VerCategoriaActionPerformed

    private void JTABLE_Mant_CategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_Mant_CategoriaMouseClicked
int filaSeleccionada = JTABLE_Mant_Categoria.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String codigo = JTABLE_Mant_Categoria.getValueAt(filaSeleccionada, 0).toString();
            String nombre = JTABLE_Mant_Categoria.getValueAt(filaSeleccionada, 1).toString();
            String descripcion = JTABLE_Mant_Categoria.getValueAt(filaSeleccionada, 2) != null 
                    ? JTABLE_Mant_Categoria.getValueAt(filaSeleccionada, 2).toString() : "";

            txtcodigoCategoria1.setText(codigo);
            txtnombreCategoria.setText(nombre);
            txtdescripcion.setText(descripcion);

            txtnombreCategoria.setEnabled(true);
            BTN_Modificar.setEnabled(true);
            BTN_Guardar.setEnabled(false);
        }
    }//GEN-LAST:event_JTABLE_Mant_CategoriaMouseClicked

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
txtcodigoCategoria1.setText("");
        txtnombreCategoria.setText("");
        txtdescripcion.setText("");
        
        txtnombreCategoria.requestFocus();
        txtnombreCategoria.setEnabled(true);
        
        BTN_Guardar.setEnabled(true);
        BTN_Modificar.setEnabled(false);
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
String nombre = txtnombreCategoria.getText().trim();
        String descripcion = txtdescripcion.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre de la Categoría",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            txtnombreCategoria.requestFocus();
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Desea guardar el registro de la Categoría?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.insertarCategoria(nombre, descripcion);

                JOptionPane.showMessageDialog(this, "Categoría registrada correctamente",
                        "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);

                this.mostrarCategorias();

                // Limpiar campos después de guardar
                txtcodigoCategoria1.setText("");
                txtnombreCategoria.setText("");
                txtdescripcion.setText("");
                BTN_Guardar.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al registrar Categoría:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
String codStr = txtcodigoCategoria1.getText().trim();
        String nombre = txtnombreCategoria.getText().trim();
        String descripcion = txtdescripcion.getText().trim();

        if (codStr.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una categoría de la tabla y complete el nombre",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int codigo = Integer.parseInt(codStr);

        int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Desea modificar esta categoría?", "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.modificarCategoria(codigo, nombre, descripcion);

                JOptionPane.showMessageDialog(this, "Categoría modificada correctamente",
                        "Modificación exitosa", JOptionPane.INFORMATION_MESSAGE);

                this.mostrarCategorias();

                // Limpiar campos y bloquear botones tras modificar
                txtcodigoCategoria1.setText("");
                txtnombreCategoria.setText("");
                txtdescripcion.setText("");
                BTN_Modificar.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al modificar categoría:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void TXT_BuscarCategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarCategoriaKeyReleased
String texto = TXT_BuscarCategoria.getText().trim();

if (texto.isEmpty()) {
    this.mostrarCategorias();
} else {
    this.buscarCategorias(texto);
}
    }//GEN-LAST:event_TXT_BuscarCategoriaKeyReleased

    private void TXT_BuscarCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarCategoriaKeyTyped

    }//GEN-LAST:event_TXT_BuscarCategoriaKeyTyped

    private void BTN_Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Cerrar1ActionPerformed
int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas cerrar el formulario?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                conexionBD.cerrarConexion();
            } catch (Exception e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
            dispose();
        }
    }//GEN-LAST:event_BTN_Cerrar1ActionPerformed

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        
    }//GEN-LAST:event_txtdescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_categoria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar1;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_VerCategoria;
    private javax.swing.JTable JTABLE_Mant_Categoria;
    private javax.swing.JTextField TXT_BuscarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcodigoCategoria1;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtnombreCategoria;
    // End of variables declaration//GEN-END:variables

public void mostrarCategorias() {
    // 1. Obtener el modelo de la tabla de la interfaz gráfica
    DefaultTableModel modeloTablaCategoria = (DefaultTableModel) JTABLE_Mant_Categoria.getModel();
    
    // 2. Limpiar las filas previas
    modeloTablaCategoria.setRowCount(0);

    try {
        // 3. Crear la instancia de conexión (usa conexionBD o conexionBD_gabriel)
        conexionBD_gabriel con = new conexionBD_gabriel();
        
        // 4. Obtener los datos llamando a listarCategorias()
        ResultSet rs = con.listarCategorias();

        // 5. Cargar las filas en la JTable
        while (rs.next()) {
            Object[] fila = new Object[3];
            fila[0] = rs.getInt(1);    // ID / Código
            fila[1] = rs.getString(2); // Nombre
            fila[2] = rs.getString(3); // Descripción
            
            modeloTablaCategoria.addRow(fila);
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error al cargar las categorías: " + ex.getMessage(), 
            "Error de Base de Datos", 
            JOptionPane.ERROR_MESSAGE);
    }
}
public void buscarCategorias(String textoBusqueda) {
    DefaultTableModel modeloTablaCategoria = (DefaultTableModel) JTABLE_Mant_Categoria.getModel();
    modeloTablaCategoria.setRowCount(0);

    try {
        conexionBD_gabriel con = new conexionBD_gabriel();
        ResultSet rs = con.buscarCategorias(textoBusqueda);

        while (rs.next()) {
            Object[] fila = new Object[3];
            fila[0] = rs.getInt(1);    // Código
            fila[1] = rs.getString(2); // Nombre
            fila[2] = rs.getString(3); // Descripción
            
            modeloTablaCategoria.addRow(fila);
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, 
            "Error al buscar categorías: " + ex.getMessage(), 
            "Error de Base de Datos", 
            JOptionPane.ERROR_MESSAGE);
    }
}
private void txtbuscarCategoriaKeyReleased(java.awt.event.KeyEvent evt) {                                             
    String texto = TXT_BuscarCategoria.getText().trim();
    
    // Si la caja de texto está vacía, muestra todas las categorías de nuevo
    if (texto.isEmpty()) {
        this.mostrarCategorias();
    } else {
        this.buscarCategorias(texto);
    }
}
}
