
package proyecto_almacen;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_producto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_producto.class.getName());
   
    /* Modelo para mostrar datos en la tabla */
    DefaultTableModel modeloTablaProducto = new DefaultTableModel();

    /* Objeto de conexión a la base de datos */
    conexionBD_gabriel conexionBD;
    
    public frm_producto() {
        setUndecorated(true);
        initComponents();
        txt_idproducto1.setEnabled(false);
        txt_codigoproducto.setEditable(true);
        txt_nombreproducto1.setEditable(true);
        txt_PrecioVenta1.setEditable(true);
        txt_unidadmedida.setEditable(true);
        jComboBox_Subcategoria.setEnabled(true);

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        BTN_Dardebaja.setEnabled(false);
                
        setLocationRelativeTo(null);


        // Crear la conexión al iniciar el formulario
        conexionBD = new conexionBD_gabriel();

        // Verificar que la conexión fue exitosa
        if (conexionBD.getConnection() == null) {
            JOptionPane.showMessageDialog(null, "No se pudo conectar con la base de datos.",
                    "Error de conexión", JOptionPane.ERROR_MESSAGE);
            return; // Evita continuar si no hay conexión
        }

        // Cargar las subcategorías en el JComboBox
        this.cargarSubcategorias();

        // Definir los encabezados de la tabla alineados a vw_producto_activo
        String titulos[] = {"ID", "ID Subcat", "Subcategoría", "Código", "Nombre Producto", "Precio Venta", "Unidad Medida"};

        // Asignar los títulos al modelo
        modeloTablaProducto.setColumnIdentifiers(titulos);

        // Establecer el modelo a la JTable
        JTABLE_Mant_producto.setModel(modeloTablaProducto);

        // Ocultar la columna ID Subcategoria (índice 1) para mantener limpia la interfaz
        JTABLE_Mant_producto.getColumnModel().getColumn(1).setMinWidth(0);
        JTABLE_Mant_producto.getColumnModel().getColumn(1).setMaxWidth(0);
        JTABLE_Mant_producto.getColumnModel().getColumn(1).setWidth(0);

        // Deshabilitar campo de ID Producto (es autogenerado)
        txt_idproducto1.setEnabled(false);
    }

    /* Método para llenar el JComboBox con las subcategorías */
    private void cargarSubcategorias() {
        jComboBox_Subcategoria.removeAllItems();
        jComboBox_Subcategoria.addItem("-- Seleccionar --");
        try {
            String sql = "SELECT id_subcategoria, nombre_subcategoria FROM subcategoria";
            Statement st = conexionBD.getConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                jComboBox_Subcategoria.addItem(rs.getInt("id_subcategoria") + " - " + rs.getString("nombre_subcategoria"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar subcategorías:\n" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /* Método auxiliar para obtener el ID de la subcategoría seleccionada en el ComboBox */
    private int obtenerIdSubcategoriaSeleccionada() {
        if (jComboBox_Subcategoria.getSelectedIndex() <= 0) {
            return 0;
        }
        String item = jComboBox_Subcategoria.getSelectedItem().toString();
        String[] partes = item.split(" - ");
        return Integer.parseInt(partes[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_codigoproducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_Subcategoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_unidadmedida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_idproducto1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nombreproducto1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_PrecioVenta1 = new javax.swing.JTextField();
        BTN_VerProducto = new javax.swing.JButton();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        BTN_Dardebaja = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TXT_BuscarProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mant_producto = new javax.swing.JTable();
        BTN_PDF = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        BTN_Cerrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MANTENIMIENTO DE PRODUCTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Subcategoria");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txt_codigoproducto.addActionListener(this::txt_codigoproductoActionPerformed);
        jPanel2.add(txt_codigoproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, 30));

        jLabel3.setText("Codigo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jComboBox_Subcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox_Subcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, 30));

        jLabel4.setText("Unidad Medida");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        txt_unidadmedida.addActionListener(this::txt_unidadmedidaActionPerformed);
        jPanel2.add(txt_unidadmedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 180, 30));

        jLabel5.setText("ID Producto");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_idproducto1.addActionListener(this::txt_idproducto1ActionPerformed);
        jPanel2.add(txt_idproducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 180, 30));

        jLabel6.setText("Nombre Producto");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, 20));

        txt_nombreproducto1.addActionListener(this::txt_nombreproducto1ActionPerformed);
        jPanel2.add(txt_nombreproducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 180, 30));

        jLabel7.setText("Precio Venta");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        txt_PrecioVenta1.addActionListener(this::txt_PrecioVenta1ActionPerformed);
        jPanel2.add(txt_PrecioVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 180, 30));

        BTN_VerProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_VerProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papel.png"))); // NOI18N
        BTN_VerProducto.setText("VER PRODUCTO");
        BTN_VerProducto.addActionListener(this::BTN_VerProductoActionPerformed);
        jPanel2.add(BTN_VerProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 180, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 840, 170));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        jPanel1.add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disco-flexible (1).png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        jPanel1.add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 190, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ahorrar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        jPanel1.add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 200, 50));

        BTN_Dardebaja.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Dardebaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/expediente.png"))); // NOI18N
        BTN_Dardebaja.setText("Dar de baja");
        BTN_Dardebaja.addActionListener(this::BTN_DardebajaActionPerformed);
        jPanel1.add(BTN_Dardebaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 180, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingresar el Nombre deL Producto");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        TXT_BuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarProductoKeyTyped(evt);
            }
        });
        jPanel3.add(TXT_BuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel9.setText("BUSCAR");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 810, 50));

        JTABLE_Mant_producto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mant_producto.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mant_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTABLE_Mant_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_Mant_productoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mant_producto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 810, 220));

        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/archivo-de-acrobat-reader.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        jPanel1.add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 120, 40));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        jPanel1.add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 120, 40));

        BTN_Cerrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrado.png"))); // NOI18N
        BTN_Cerrar1.setText("Cerrar");
        BTN_Cerrar1.addActionListener(this::BTN_Cerrar1ActionPerformed);
        jPanel1.add(BTN_Cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoproductoActionPerformed

    private void txt_unidadmedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unidadmedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unidadmedidaActionPerformed

    private void txt_idproducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idproducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idproducto1ActionPerformed

    private void txt_nombreproducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreproducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreproducto1ActionPerformed

    private void txt_PrecioVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PrecioVenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PrecioVenta1ActionPerformed

    private void BTN_VerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VerProductoActionPerformed
        this.MostrarProductos();
    }//GEN-LAST:event_BTN_VerProductoActionPerformed

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
        txt_idproducto1.setText("");
        txt_codigoproducto.setText("");
        txt_nombreproducto1.setText("");
        txt_PrecioVenta1.setText("");
        txt_unidadmedida.setText("");
        if (jComboBox_Subcategoria.getItemCount() > 0) {
            jComboBox_Subcategoria.setSelectedIndex(0);
        }

        txt_codigoproducto.requestFocus();

        BTN_Guardar.setEnabled(true);
        BTN_Modificar.setEnabled(false);
        BTN_Dardebaja.setEnabled(false);
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
        int idSubcategoria = obtenerIdSubcategoriaSeleccionada();
        String codigo = txt_codigoproducto.getText().trim();
        String nombre = txt_nombreproducto1.getText().trim();
        String precioStr = txt_PrecioVenta1.getText().trim();
        String unidad = txt_unidadmedida.getText().trim();

        if (idSubcategoria == 0 || codigo.isEmpty() || nombre.isEmpty() || precioStr.isEmpty() || unidad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos requeridos.",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double precio = 0;
        try {
            precio = Double.parseDouble(precioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un precio de venta válido.",
                    "Validación", JOptionPane.WARNING_MESSAGE);
            txt_PrecioVenta1.requestFocus();
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea guardar el registro del Producto?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.insertarProducto(idSubcategoria, codigo, nombre, precio, unidad);

                JOptionPane.showMessageDialog(null, "Producto registrado correctamente",
                        "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarProductos();

                txt_idproducto1.setText("");
                txt_codigoproducto.setText("");
                txt_nombreproducto1.setText("");
                txt_PrecioVenta1.setText("");
                txt_unidadmedida.setText("");
                jComboBox_Subcategoria.setSelectedIndex(0);

                BTN_Guardar.setEnabled(false);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al registrar Producto:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
        String idStr = txt_idproducto1.getText().trim();
        int idSubcategoria = obtenerIdSubcategoriaSeleccionada();
        String codigo = txt_codigoproducto.getText().trim();
        String nombre = txt_nombreproducto1.getText().trim();
        String precioStr = txt_PrecioVenta1.getText().trim();
        String unidad = txt_unidadmedida.getText().trim();

        if (idStr.isEmpty() || idSubcategoria == 0 || codigo.isEmpty() || nombre.isEmpty() || precioStr.isEmpty() || unidad.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla y complete todos los campos.",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idProducto = Integer.parseInt(idStr);
        double precio = 0;
        try {
            precio = Double.parseDouble(precioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un precio de venta válido.",
                    "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea modificar este producto?", "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.modificarProducto(idProducto, idSubcategoria, codigo, nombre, precio, unidad);

                JOptionPane.showMessageDialog(null, "Producto modificado correctamente",
                        "Modificación exitosa", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarProductos();

                txt_idproducto1.setText("");
                txt_codigoproducto.setText("");
                txt_nombreproducto1.setText("");
                txt_PrecioVenta1.setText("");
                txt_unidadmedida.setText("");
                jComboBox_Subcategoria.setSelectedIndex(0);

                BTN_Modificar.setEnabled(false);
                BTN_Dardebaja.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al modificar producto:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_DardebajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DardebajaActionPerformed
        String idStr = txt_idproducto1.getText().trim();

        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla para dar de baja.",
                    "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idProducto = Integer.parseInt(idStr);

        int respuesta = JOptionPane.showConfirmDialog(null,
                "¿Desea dar de baja este producto?", "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            try {
                conexionBD.desactivarProducto(idProducto);

                JOptionPane.showMessageDialog(null, "Producto dado de baja correctamente",
                        "Desactivación exitosa", JOptionPane.INFORMATION_MESSAGE);

                this.MostrarProductos();

                txt_idproducto1.setText("");
                txt_codigoproducto.setText("");
                txt_nombreproducto1.setText("");
                txt_PrecioVenta1.setText("");
                txt_unidadmedida.setText("");
                jComboBox_Subcategoria.setSelectedIndex(0);

                BTN_Modificar.setEnabled(false);
                BTN_Dardebaja.setEnabled(false);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al dar de baja el producto:\n"
                        + ex.getMessage(), "Error de base de datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BTN_DardebajaActionPerformed

    private void TXT_BuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarProductoKeyReleased
this.buscarProductos();
    }//GEN-LAST:event_TXT_BuscarProductoKeyReleased

    private void TXT_BuscarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarProductoKeyTyped

    }//GEN-LAST:event_TXT_BuscarProductoKeyTyped

    private void JTABLE_Mant_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_Mant_productoMouseClicked
        int filaSeleccionada = JTABLE_Mant_producto.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String id = JTABLE_Mant_producto.getValueAt(filaSeleccionada, 0).toString();
            int idSubcategoria = Integer.parseInt(JTABLE_Mant_producto.getValueAt(filaSeleccionada, 1).toString());
            String codigo = JTABLE_Mant_producto.getValueAt(filaSeleccionada, 3) != null ? JTABLE_Mant_producto.getValueAt(filaSeleccionada, 3).toString() : "";
            String nombre = JTABLE_Mant_producto.getValueAt(filaSeleccionada, 4) != null ? JTABLE_Mant_producto.getValueAt(filaSeleccionada, 4).toString() : "";
            String precio = JTABLE_Mant_producto.getValueAt(filaSeleccionada, 5) != null ? JTABLE_Mant_producto.getValueAt(filaSeleccionada, 5).toString() : "";
            String unidad = JTABLE_Mant_producto.getValueAt(filaSeleccionada, 6) != null ? JTABLE_Mant_producto.getValueAt(filaSeleccionada, 6).toString() : "";

            txt_idproducto1.setText(id);
            txt_codigoproducto.setText(codigo);
            txt_nombreproducto1.setText(nombre);
            txt_PrecioVenta1.setText(precio);
            txt_unidadmedida.setText(unidad);

            // Seleccionar en el JComboBox la subcategoría correspondiente por ID
            for (int i = 0; i < jComboBox_Subcategoria.getItemCount(); i++) {
                String item = jComboBox_Subcategoria.getItemAt(i);
                if (item.startsWith(idSubcategoria + " - ")) {
                    jComboBox_Subcategoria.setSelectedIndex(i);
                    break;
                }
            }

            BTN_Modificar.setEnabled(true);
            BTN_Dardebaja.setEnabled(true);
            BTN_Guardar.setEnabled(false);
        }
    }//GEN-LAST:event_JTABLE_Mant_productoMouseClicked

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void BTN_Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Cerrar1ActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas cerrar el formulario?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                conexionBD.cerrarConexion();
            } catch (Exception e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
            dispose();
        }
    }//GEN-LAST:event_BTN_Cerrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_producto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar1;
    private javax.swing.JButton BTN_Dardebaja;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_VerProducto;
    private javax.swing.JTable JTABLE_Mant_producto;
    private javax.swing.JTextField TXT_BuscarProducto;
    private javax.swing.JComboBox<String> jComboBox_Subcategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_PrecioVenta1;
    private javax.swing.JTextField txt_codigoproducto;
    private javax.swing.JTextField txt_idproducto1;
    private javax.swing.JTextField txt_nombreproducto1;
    private javax.swing.JTextField txt_unidadmedida;
    // End of variables declaration//GEN-END:variables
public void MostrarProductos() {
        txt_nombreproducto1.setEnabled(true);
        JTABLE_Mant_producto.setAutoCreateRowSorter(true);
        modeloTablaProducto.setRowCount(0);
        try {
            ResultSet rs = conexionBD.listarProductos();
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_producto"),
                    rs.getInt("id_subcategoria"),
                    rs.getString("nombre_subcategoria"),
                    rs.getString("codigo"),
                    rs.getString("nombre_producto"),
                    rs.getDouble("precio_venta"),
                    rs.getString("unidad_medida")
                };
                modeloTablaProducto.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Productos:\n" + e.getMessage(),
                    "Error de consulta", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void buscarProductos() {
        modeloTablaProducto.setRowCount(0);
        String busqueda = TXT_BuscarProducto.getText().trim();
        try {
            ResultSet rs = conexionBD.buscarProductos(busqueda);
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_producto"),
                    rs.getInt("id_subcategoria"),
                    rs.getString("nombre_subcategoria"),
                    rs.getString("codigo"),
                    rs.getString("nombre_producto"),
                    rs.getDouble("precio_venta"),
                    rs.getString("unidad_medida")
                };
                modeloTablaProducto.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Error al buscar Productos:\n" + e.getMessage(),
                    "Error de búsqueda", JOptionPane.ERROR_MESSAGE);
        }
    }
}
